### ISSUE TITLE
Error with Opening Cases

### ISSUE THREAD

**Issue by Sully231** [GreWeMa/gwm_Crates#11]
Hello, I am currently having problems with opening the "GWM_Crates" cases. Whenever I attempt to open them with the corresponding key, I receive this in my server logs.

![log screenshot](https://user-images.githubusercontent.com/35669679/35199288-4ade829c-feca-11e7-91c0-20ae987d87c0.PNG)
![log screenshot 2](https://user-images.githubusercontent.com/35669679/35199364-81fb9ee0-feca-11e7-9a45-090f3e709452.PNG)

**SpongeAPI Version**: 7.0.0 Snapshot

**GWM_Crates Version**: Tried both beta 2.2.2 and beta 2.2. Currently using beta 2.2

The current config I am using is almost an exact copy of your second example, however it still isn't working for my server. 

NAME: "Sword Crate"
ID: "sword_crate"
CASE: {
    TYPE: "BLOCK"
    HOLOGRAM: "&aSword Crate"
    LOCATION: {
        WORLD_NAME: "world"
        X: -88
        Y: 85
        Z: 192
    }
    START_PREVIEW_ON_LEFT_CLICK: true
}
KEY: {
    TYPE: "ITEM"
    PRICE: 100
    ITEM: {
		ITEM_TYPE: "minecraft:tripwire_hook"
		DISPLAY_NAME: "&4Sword Crate Key"
		LORE: [
			"&6Try your luck&0!"
			"&aSword Crate &6Key!"
		]
	}
}
OPEN_MANAGER: {
    TYPE: "FIRST"
    OPEN_SOUND: "block.anvil.use"
    SCROLL_SOUND: "entity.firework.shoot"
    WIN_SOUND: "entity.experience_orb.pickup"
    DISPLAY_NAME: "&2First Sword Crate"
    DECORATIVE_ITEMS_CHANGE_MODE: {
        TYPE: "RANDOM"
        CHANGE_DELAY: 5
        IGNORED_INDICES: [
            4,
            9,
            10,
            15
        ]
    }
    DECORATIVE_ITEMS: [
        {
            ITEM_TYPE: EMERALD
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: DIAMOND
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: EMERALD
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: EMERALD
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: DIAMOND
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: PLANKS
        }, {
            ITEM_TYPE: EMERALD
        }
    ]
    SCROLL_DELAYS: [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        5,
        5,
        5,
        5,
        5,
        5,
        6,
        6,
        6,
        6,
        6,
        7,
        7,
        7,
        7,
        8,
        8,
        8,
        9,
        9,
        10,
        20,
        40
    ]
    CLEAR_DECORATIVE_ITEMS: false
    CLEAR_OTHER_DROPS: true
    CLOSE_DELAY: 60
}
PREVIEW: {
    TYPE: "FIRST"
    DISPLAY_NAME: "&2First Sword Crate Preview"
    DECORATIVE_ITEMS: [
        {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 1
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 2
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 3
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 4
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 5
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 6
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 7
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 8
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 9
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 10
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 10
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 9
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 8
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 7
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 6
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 5
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 4
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 3
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 2
        }, {
            ITEM_TYPE: "minecraft:stained_glass_pane"
            SUB_ID: 1
        }
    ]
    SCROLL_DELAY: 10
}
DROPS: [
    {
        TYPE: "MULTI"
        ID: "wooden_sword"
        LEVEL: 1
        DROP_ITEM: {
            ITEM_TYPE: "minecraft:wooden_sword"
        }
        DROPS: [
            {
                TYPE: "ITEM"
                ID: "wooden_sword_item"
                ITEM: {
                    ITEM_TYPE: "minecraft:wooden_sword"
                }
            }, {
                TYPE: "COMMANDS"
                ID: "wooden_sword_command"
                COMMANDS: [
                    {
                        CMD: "say %PLAYER% won wooden sword!"
                        CONSOLE: true
                    }, {
                        CMD: "tell %PLAYER% Congratulations! You won wooden sword!"
                        CONSOLE: true
                    }
                ]
            }
        ]
    }, {
        TYPE: "MULTI"
        ID: "stone_sword"
        LEVEL: 2
        FAKE_LEVEL: 1
        DROP_ITEM: {
            ITEM_TYPE: "minecraft:stone_sword"
        }
        DROPS: [
            {
                TYPE: "ITEM"
                ID: "stone_sword_item"
                ITEM: {
                    ITEM_TYPE: "minecraft:stone_sword"
                }
            }, {
                TYPE: "COMMANDS"
                ID: "stone_sword_command"
                COMMANDS: [
                    {
                        CMD: "say %PLAYER% won stone sword!"
                        CONSOLE: true
                    }, {
                        CMD: "tell %PLAYER% Congratulations! You won stone sword!"
                        CONSOLE: true
                    }
                ]
            }
        ]
    }, {
        TYPE: "MULTI"
        ID: "golden_sword"
        LEVEL: 3
        FAKE_LEVEL: 1
        DROP_ITEM: {
            ITEM_TYPE: "minecraft:golden_sword"
        }
        DROPS: [
            {
                TYPE: "ITEM"
                ID: "golden_sword_item"
                ITEM: {
                    ITEM_TYPE: "minecraft:golden_sword"
                }
            }, {
                TYPE: "COMMANDS"
                ID: "golden_sword_command"
                COMMANDS: [
                    {
                        CMD: "say %PLAYER% won golden sword!"
                        CONSOLE: true
                    }, {
                        CMD: "tell %PLAYER% Congratulations! You won golden sword!"
                        CONSOLE: true
                    }
                ]
            }
        ]
    }, {
        TYPE: "MULTI"
        ID: "iron_sword"
        LEVEL: 4
        FAKE_LEVEL: 2
        DROP_ITEM: {
            ITEM_TYPE: "minecraft:iron_sword"
        }
        DROPS: [
            {
                TYPE: "ITEM"
                ID: "iron_sword_item"
                ITEM: {
                    ITEM_TYPE: "minecraft:iron_sword"
                }
            }, {
                TYPE: "COMMANDS"
                ID: "iron_sword_command"
                COMMANDS: [
                    {
                        CMD: "say %PLAYER% won iron sword!"
                        CONSOLE: true
                    }, {
                        CMD: "tell %PLAYER% Congratulations! You won iron sword!"
                        CONSOLE: true
                    }
                ]
            }
        ]
    }, {
        TYPE: "MULTI"
        ID: "diamond_sword"
        LEVEL: 5
        FAKE_LEVEL: 3
        DROP_ITEM: {
            ITEM_TYPE: "minecraft:diamond_sword"
        }
        DROPS: [
            {
                TYPE: "ITEM"
                ID: "diamond_sword_item"
                ITEM: {
                    ITEM_TYPE: "minecraft:diamond_sword"
                }
            }, {
                TYPE: "COMMANDS"
                ID: "diamond_sword_command"
                COMMANDS: [
                    {
                        CMD: "say %PLAYER% won diamond sword!"
                        CONSOLE: true
                    }, {
                        CMD: "tell %PLAYER% Congratulations! You won diamond sword!"
                        CONSOLE: true
                    }
                ]
            }
        ]
    }
]

**Comment by GreWeMa** [comment]
You are using old API 7 Sponge build.
You need upgrade your Sponge, or use special GWMCrates build for versions of sponge below Vanilla BETA-1 / Forge 2815 (you can find this in 'gwm_crates' discord channel pinned messages).
But upgrading your Sponge build is more preferable!
