### ISSUE TITLE
CLEAR_DECORATIVE_ITEMS not clearing all the items

### ISSUE THREAD

**Issue by kaal-1** [GreWeMa/gwm_Crates#2]
Latest SpongeForge 1.10.2
I have different color glass panes all around, and when the crate finishes the animation, only some of them get cleared out. See:
![image](https://user-images.githubusercontent.com/9734718/28575058-2e968490-7126-11e7-8310-75b53023e253.png)

**Comment by iLefty** [comment]
Are you use last version of GWM_Crates?

**Comment by kaal-1** [comment]
Yes I'm using the last version, downloaded it from the releases tab.

**Comment by GreWeMa** [comment]
Thank you for posting issue!
I found where bug is located, and will release fix in the next couple of minutes/hours.
