### ISSUE TITLE
NoClassDefFoundError: org/spongepowered/api/item/Enchantments

### ISSUE THREAD

**Issue by ziceptor** [GreWeMa/gwm_Crates#7]
`/gwmcrates gui` в консоли выдаёт https://gist.github.com/ziceptor/717cddf0a29d4de13aa9a4b75ad4c795

forge-1.12.2-14.23.1.2555-universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2780.jar
GWMCrates.jar последний с ore

**Comment by GreWeMa** [comment]
Должно работать с последним билдом Sponge и последней версией кейсов.

**Comment by ziceptor** [comment]
Ограничен во времени. Проверю когда будут реализованы #9 и #10

**Comment by PixelmonPRO** [comment]
Работает
