### ISSUE TITLE
Could not pass InteractBlockEvent$Primary$MainHand$Impl

### ISSUE THREAD

**Issue by ziceptor** [GreWeMa/gwm_Crates#8]
Попытка сломать в креативе ящик, даёт это https://gist.github.com/ziceptor/fdd6df9535edd0ea5af1bfb2fae415e4

Используется example_manager2.conf

forge-1.12.2-14.23.1.2555-universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2780.jar
GWMCrates.jar последний с ore

**Comment by GreWeMa** [comment]
Должно работать с последним билдом Sponge и последней версией кейсов.

**Comment by ziceptor** [comment]
Ограничен во времени. Проверю когда будут реализованы #9 и #10

**Comment by GreWeMa** [comment]
В общем мною протестировано (на последней версии плагина и Sponge) - баг не повторяется.
